### ISSUE TITLE
Failure to recognize some URLs of AOJ

### ISSUE THREAD

**Issue by kmyk** [online-judge-tools/oj#737]
<blockquote class="twitter-tweet" data-partner="tweetdeck"><p lang="ja" dir="ltr">online-judge-toolsとかonline-judge-verify-helperでAOJのbeta版の方のURL(<a href="https://t.co/0BSPdi4t44">https://t.co/0BSPdi4t44</a>とか)が動かないことあるのって仕様なんだろうか</p>&mdash; けんしん (@knshnb) <a href="https://twitter.com/knshnb/status/1254453954714300416?ref_src=twsrc%5Etfw">April 26, 2020</a></blockquote>

https://onlinejudge.u-aizu.ac.jp/problems/0423

``` console
$ oj --version
online-judge-tools 9.2.1
$ oj -v d -n https://onlinejudge.u-aizu.ac.jp/problems/0423
[DEBUG] args: Namespace(cookie=PosixPath('/home/ubuntu/.local/share/online-judge-tools/cookie.jar'), directory=None, dry_run=True, format=None, json=False, silent=False, subcommand='d', system=False, url='https://onlinejudge.u-aizu.ac.jp/problems/0423', verbose=True, version=False, yukicoder_token=None)
[-] unknown problem: https://onlinejudge.u-aizu.ac.jp/problems/0423
[DEBUG] 
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/onlinejudge/_implementation/main.py", line 233, in main
    run_program(namespace, parser=parser)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/onlinejudge/_implementation/main.py", line 208, in run_program
    download(args)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/onlinejudge/_implementation/command/download.py", line 34, in download
    raise requests.exceptions.InvalidURL('The contest "%s" is not supported' % args.url)
requests.exceptions.InvalidURL: The contest "https://onlinejudge.u-aizu.ac.jp/problems/0423" is not supported

[ERROR] The contest "https://onlinejudge.u-aizu.ac.jp/problems/0423" is not supported
```

**Comment by kmyk** [comment]
@knshnb よければプルリクしてみませんか？

**Comment by knshnb** [comment]
#738 
@kmyk 作ってみました。ご確認いただけるとありがたいです。
