### ISSUE TITLE
An `AssertionError` happens when try to submit to atcoder

### ISSUE THREAD

**Issue by kazu914** [online-judge-tools/oj#792]
## Description
When I try to submit my program file to atcoder, the below error happens.

### env

```console
> uname -a   
Linux thinkPad 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

> pyhton3 -V
Python 3.8.2

> pip3 freeze | grep online  
online-judge-api-client==10.2.5
online-judge-tools==10.0.5

```

The command I run is

```console
oj -v s https://atcoder.jp/contests/abc174/tasks/abc174_a main.py     
```

## Error log

``` console
[DEBUG] args: Namespace(cookie=PosixPath('/home/nomura/.local/share/online-judge-tools/cookie.jar'), file=PosixPath('main.py'), format_dos2unix=False, format_rstrip=False, golf=False, guess=True, guess_cxx_compiler='gcc', guess_cxx_latest=True, guess_python_interpreter='cpython', guess_python_version='auto', language=None, open=True, subcommand='s', url='https://atcoder.jp/contests/abc174/tasks/abc174_a', verbose=True, version=False, wait=3, yes=False)
[*] online-judge-tools 10.0.5 (+ online-judge-api-client 10.2.5)
[*] code (343 byte):

**My solution here**

[DEBUG] User-Agent: online-judge-tools/10.0.5 (+https://github.com/online-judge-tools/oj)
[DEBUG] 
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.8/site-packages/onlinejudge_command/main.py", line 232, in main
    run_program(namespace, parser=parser)
  File "/home/user/.local/lib/python3.8/site-packages/onlinejudge_command/main.py", line 211, in run_program
    submit(args)
  File "/home/user/.local/lib/python3.8/site-packages/onlinejudge_command/subcommand/submit.py", line 57, in submit
    language_dict = {language.id: language.name for language in problem.get_available_languages(session=sess)}  # type: Dict[LanguageId, str]
  File "/home/user/.local/lib/python3.8/site-packages/onlinejudge/service/atcoder.py", line 871, in get_available_languages
    data = self.download_data(session=session)
  File "/home/user/.local/lib/python3.8/site-packages/onlinejudge/service/atcoder.py", line 806, in download_data
    return AtCoderProblemDetailedData.from_html(html, problem=self, session=session, response=resp, timestamp=timestamp)
  File "/home/user/.local/lib/python3.8/site-packages/onlinejudge/service/atcoder.py", line 765, in from_html
    data = AtCoderProblemData._from_html(html, problem=problem, session=session, response=response, timestamp=timestamp)
  File "/home/user/.local/lib/python3.8/site-packages/onlinejudge/service/atcoder.py", line 568, in _from_html
    assert False
AssertionError

[ERROR] 

```

## Other notes

I found that by adding `.strip()` to line 563 in `onlinejudge/service/atcoder.py` like this, this awesome tool works fine.

```git
- time_limit, memory_limit = h2.find_next_sibling('p').text.split(' / ')
+ time_limit, memory_limit = h2.find_next_sibling('p').text.strip().split(' / ')
```

**Comment by kmyk** [comment]
Thank you @kazu914 for reporting and suggesting the patch for this!
I made the pull request for this, https://github.com/online-judge-tools/api-client/pull/85

**Comment by kmyk** [comment]
原因:

HTML 中で問題名が書かれている部分が

``` html
<span class="h2">
  A - Air Conditioner
</span>
```

という形だったのが

``` html
<span class="h2">
  A - Air Conditioner
  <a class="btn btn-default btn-sm" href="/contests/abc174/tasks/abc174_a/editorial">解説</a>
</span>
```

になった。これにより問題名の取得機能が壊れた。提出機能は中で雑に「関連する情報全部取得してきて」をやっててかつ例外処理が甘いので、これに巻き込まれて落ちた。
